runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app -t 360

runtime_config:
  python_version: 3


health_check:
  enable_health_check: False

# health_check: # not yet supported, use instead
vm_health_check:
  enable_health_check: False

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.9